title: Jonah Nathan # your name (or website title) here
logo: "/images/Jonah-LinkedIn.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/jonah-nathan/">LinkedIn</a> 
  <br>
  <a href="pdf/Jonah Nathan Resume.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/jonahnathan0/">GitHub</a>  
  
theme: jekyll-theme-minimal
